### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ludo1960** [elboza/PhpQuery#1]
Hello,

I used composer: composer require phpquery/phpquery and it created a vendor folder in the root of my site. In my code i tried require_once __DIR__ . '/../vendor/autoload.php'; but that produced an error "Warning: require_once(/var/www/slim.local.com/crawl/../vendor/autoload.php): failed to open stream:" so I edited it to  require_once __DIR__ . '/vendor/autoload.php'; In this case the autoload is found. Then I try "use PhpQuery\PhpQuery ;" Again I get the error "Fatal error: Uncaught Error: Class 'PhpQuery\PhpQuery' not found in /var/www/slim.local.com/crawl/crawler6.php:25" I can see the phpquery.php in the vendor/phpquery/phpquery/src directory. I have tried various paths to try and get it working without success. Where am I going wrong?
Thanks

**Comment by hellolindsay** [comment]
I have the same issue. This is simply because the file "phpquery.php" should be "PhpQuery.php". Some servers are case sensitive, others are not. Currently, this code will only work on case insensitive systems.

**Comment by hellolindsay** [comment]
Can we change phpquery.php to PhpQuery.php, please?

**Comment by elboza** [comment]
Hi all,
sorry for the late response.
i updated the file name from 'phpquery.php' to 'PhpQuery.php' and updated the package.
i hope this will solve the issue.
