### ISSUE TITLE
Generates incorrect xpath for class name

### ISSUE THREAD

**Issue by uniquexor** [elboza/PhpQuery#3]
There are two problems with generating xpath for class names.
1. When you try to query any element, that has a "-" symbol in it's class name, the xpath generated is incorrect.
For example, if we try to query:
`$doc->query( 'span.result-count' )` 
everything after "-" gets removed and we get:
`//span[contains(@class,"result")]`
2. The generated xpath is not quite correct. As this will also match class names like "xxxxresult" or "resultxxxx".
There is a solution for this here: [stackoverflow](https://stackoverflow.com/questions/1604471/how-can-i-find-an-element-by-css-class-with-xpath)

From what I've found, for the first issue, the problem lies in PhpQuery::get_classes() method on line 27. `\w` in the regular expression `/(?<=\.)\w+/` does not include "-" symbol. Therefore it is not matched. Changing the expression to `/(?<=\.)[\w-]+/` fixes the problem, however I'm not sure if it does not introduce any unwanted behaviors...

**Comment by elboza** [comment]
Hi,
 
i applied the fix you provided for point n1. It seems not to introduce other not desired behaviour.

for point n2 i am still investigating the best solution.

**Comment by elboza** [comment]
fixed also point n2 with the solution you proposed in the link.

**Comment by uniquexor** [comment]
Thanks
